name: scala-with-cats-exersises-testAll
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
      - name: testAll
        run:
          sbt test